name: Contracts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
    contracts:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          with:
            submodules: recursive
            fetch-depth: 0
        - name: Install Foundry
          uses: foundry-rs/foundry-toolchain@v1
        - name: Show version
          run: forge --version
        - name: Lint Solidity code
          run: forge lint
        - name: Deployment Dry Run
          run: |
            export MANAGER_ADDRESS=0x1234567890123456789012345678901234567890
            script/deploy.sh --dry-run
        - name: Run contract tests
          run: forge test -vvv --summary