name: Contracts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
    contracts:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          with:
            submodules: recursive
            fetch-depth: 0
        - name: Install Foundry
          uses: foundry-rs/foundry-toolchain@v1
        - name: Run contract tests
          run: forge test -vvv